FROM nginx:stable-alpine

ENV WORK_DIR /etc/nginx/ssl/
ENV KEY_NAME cert
ENV COMMON_NAME localhost

WORKDIR ${WORK_DIR}

RUN apk --update add openssl

RUN echo "Making key at ${WORK_DIR}${KEY_NAME}.key"

RUN /usr/bin/openssl genrsa -out ${WORK_DIR}${KEY_NAME}.key 1024 \
    && /usr/bin/openssl req  -new -newkey rsa:4096 -days 365 \
      -nodes -subj "/C=/ST=/L=/O=/CN=${COMMON_NAME}" \
      -keyout ${WORK_DIR}${KEY_NAME}.key -out ${WORK_DIR}${KEY_NAME}.csr \
    && /usr/bin/openssl x509 -req -days 365 -in ${WORK_DIR}${KEY_NAME}.csr \
      -signkey ${WORK_DIR}${KEY_NAME}.key -out ${WORK_DIR}${KEY_NAME}.crt
